{
 "title": "01 - COVID19 - WORLD",
 "tags": [
  "CORONA-WORLD",
  "COVID-WORLD"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "query": {}
   },
   { "name": "host", "query": "$group.CORONA-COVID19" },
   { "name": "countries", "label": "Countries", "query": "$group.$host.*" },
   { "name": "todaycases", "query": "$group.$host.*.*" }
  ]
 },
 "panels": [
  { "title": "World Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "application": { "filter": "Total Cases" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total All updated" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 17, "x": 3, "y": 1 },
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/Cases .*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\".* - (.*)\" - Deaths$/",
        "$1"
       ],
       "text": "replaceAlias(/\".* - (.*)\" - Deaths$/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\".*\" - Deaths/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 1 },
   "content": "<br><br><br><br><div class=\"text-center\"><br>\n<br><h2 style=\"line-height: 45px; margin: 0; color: #bbb;\">CORONA VIRUS WORLD</h2><br><h4></a>Data Sources: <a href=\"https://www.worldometers.info/coronavirus\" target=\"_blank\">https://www.worldometers.info/coronavirus</a> and <a href=\"https://corona.lmao.ninja\" target=\"_blank\">https://corona.lmao.ninja</a><br><br>Obs: Data contained in this panel are for testing purposes of the tool</h4>\n<a href=\"https://medium.com/@bernardolankheet\" target=\"_blank\">https://medium.com/@bernardolankheet</a></div>\n\n\n\n\n\n"
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "targets": [
    {
     "application": { "filter": "Total Cases" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total All Cases" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "targets": [
    {
     "application": { "filter": "Total Cases" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total All Recovered" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "targets": [
    {
     "application": { "filter": "Total Cases" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total All Deaths" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "World Statistics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Total Cases" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Total All (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Total All (.*)/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/^(?:(?!updated).)+$/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TOP 10 - Countries with Confirmed Cases",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "application": { "filter": "/Cases .*/" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "avg"
       ],
       "text": "top(10, avg)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\"(.*) - .*\" - ActiveCases/",
        "$1"
       ],
       "text": "replaceAlias(/\"(.*) - .*\" - ActiveCases/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* - ActiveCases/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TOP 10 - Deaths",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/Cases .*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\"(.*) - .*\" - Deaths/",
        "$1"
       ],
       "text": "replaceAlias(/\"(.*) - .*\" - Deaths/, $1)"
      },
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "avg"
       ],
       "text": "top(10, avg)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* - Deaths/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TOP 10 - Today Confirmed Cases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/Cases .*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\"(.*) - .*\" - TodayCases/",
        "$1"
       ],
       "text": "replaceAlias(/\"(.*) - .*\" - TodayCases/, $1)"
      },
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "avg"
       ],
       "text": "top(10, avg)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* - TodayCases/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Estatisticas $countries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "countries" },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 28 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Cases$/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 28 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - ActiveCases/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 28 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Critical/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 28 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Deaths$/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 28 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Recovered/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 28 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - TodayCases/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 28 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - TodayDeaths/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 28 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - CasesPerOneMillion/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 28 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - DeathsPerOneMillion/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Estatisticas $countries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Cases$/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - ActiveCases/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Critical/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Deaths$/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Recovered/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - TodayCases/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - TodayDeaths/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - CasesPerOneMillion/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - DeathsPerOneMillion/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Estatisticas $countries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 36 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Cases$/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 36 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - ActiveCases/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 36 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Critical/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 36 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Deaths$/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 36 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Recovered/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 36 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - TodayCases/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 36 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - TodayDeaths/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 36 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - CasesPerOneMillion/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 36 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - DeathsPerOneMillion/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Estatisticas $countries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 40 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Cases$/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 40 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - ActiveCases/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 40 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Critical/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 40 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Deaths$/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 40 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - Recovered/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 40 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - TodayCases/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 40 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - TodayDeaths/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 40 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - CasesPerOneMillion/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 40 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Cases \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries - .*\" - DeathsPerOneMillion/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}